<script setup lang="ts">
import { VueGoodTable } from 'vue-good-table-next';
import 'vue-good-table-next/dist/vue-good-table-next.css';

import Header from '~/components/Header.vue';
import Footer from '~/components/Footer.vue';

const columns = [
    { label: "タイトル", field: "title" },
    { label: "原作", field: "author" },
    { label: "初放送", field: "year" },
    { label: "会社", field: "type" },
]

const rows = [
    { 'id': 1, 'title': 'AKIRA', 'author': '大友克洋', 'year': '1988', 'company': '東京ムービー新社' },
    { 'id': 2, 'title': '悪役令嬢転生おじさん', 'author': '上山道郎', 'year': '2025', 'company': '亜細亜堂' },
    { 'id': 3, 'title': 'あずまんが大王', 'author': 'あずまきよひこ', 'year': '2002', 'company': 'J.C.STAFF' },
    { 'id': 4, 'title': 'あずまんが大王 THE ANIMATION', 'author': 'あずまきよひこ', 'year': '2001', 'company': 'J.C.STAFF' },
    { 'id': 5, 'title': 'アニ×パラ〜あなたのヒーローは誰ですか〜', 'author': '', 'year': '2017', 'company': 'NHKエンタープライズ' },
    { 'id': 6, 'title': 'ある朝ダミーヘッドマイクになっていた俺クンの人生', 'author': 'RaRo', 'year': '2022', 'company': 'INDIVISIONEKACHI EPILKA' },
    { 'id': 7, 'title': 'アルプスの少女ハイジ', 'author': 'Johanna Spyri', 'year': '1974', 'company': 'ズイヨー映像株式会社' },
    { 'id': 8, 'title': 'うちの3姉妹', 'author': '松本ぷりっつ', 'year': '2008', 'company': '東映アニメーションSTUDIO ANIMAL' },
    { 'id': 9, 'title': '宇宙よりも遠い場所', 'author': 'よりもい', 'year': '2018', 'company': 'マッドハウス' },
    { 'id': 10, 'title': 'うっかりペネロペ', 'author': 'Georg HallenslebenAnne Gutman', 'year': '2006', 'company': '日本アニメーション' },
    { 'id': 11, 'title': '映像研には手を出すな！', 'author': '大童澄瞳', 'year': '2020', 'company': 'サイエンスSARU' },
    { 'id': 12, 'title': '江戸前エルフ', 'author': '樋口彰彦', 'year': '2023', 'company': 'C2C' },
    { 'id': 13, 'title': '王さまものがたり', 'author': '', 'year': '2007', 'company': 'ミスミヨシコ' },
    { 'id': 14, 'title': 'おおかみこどもの雨と雪', 'author': '細田守', 'year': '2012', 'company': 'スタジオ地図' },
    { 'id': 15, 'title': 'おさるのジョージ', 'author': 'Hans Augusto ReyMargret Elizabeth Rey', 'year': '2009', 'company': 'Toon City' },
    { 'id': 16, 'title': 'おじゃる丸', 'author': '犬丸りん', 'year': '1998', 'company': 'ぎゃろっぷ' },
    { 'id': 17, 'title': 'おでんくん', 'author': 'リリー・フランキー', 'year': '2005', 'company': 'エッグ' },
    { 'id': 18, 'title': 'お兄ちゃんはおしまい!', 'author': 'ねことうふ', 'year': '2023', 'company': 'スタジオバインド' },
    { 'id': 19, 'title': 'おにくだいすき!ゼウシくん', 'author': '', 'year': '2014', 'company': 'DLE' },
    { 'id': 20, 'title': '鬼警部アンパン', 'author': '', 'year': '2009', 'company': '和田敏克' },
    { 'id': 21, 'title': 'おもひでぽろぽろ', 'author': '岡本螢刀根夕子', 'year': '1991', 'company': 'スタジオジブリ' },
    { 'id': 22, 'title': '風の谷のナウシカ', 'author': '宮崎駿', 'year': '1984', 'company': 'スタジオジブリ' },
    { 'id': 23, 'title': '家庭教師ヒットマンREBORN!', 'author': '天野明', 'year': '2006', 'company': 'ARTLAND' },
    { 'id': 24, 'title': 'カペリート', 'author': '', 'year': '2001', 'company': 'Rodolfo Pastor' },
    { 'id': 25, 'title': '紙兎ロペ', 'author': '内山勇士', 'year': '2012', 'company': 'KITERETSU' },
    { 'id': 26, 'title': '（仮）兎マサル', 'author': '', 'year': '2014?', 'company': '' },
    { 'id': 27, 'title': '逆転裁判 〜その「真実」、異議あり！〜', 'author': 'カプコン', 'year': '2016', 'company': 'A-1 Pictures' },
    { 'id': 28, 'title': 'キャラとおたまじゃくし島', 'author': '寺田憲史門秀彦', 'year': '2018', 'company': '33コレクティブ' },
    { 'id': 29, 'title': 'キルミーベイベー', 'author': 'カヅホ', 'year': '2012', 'company': 'J.C.STAFF' },
    { 'id': 30, 'title': '銀河鉄道999', 'author': '松本零士', 'year': '1978', 'company': '東映動画' },
    { 'id': 31, 'title': '銀河鉄道999', 'author': '松本零士', 'year': '1979', 'company': '東映動画' },
    { 'id': 32, 'title': 'さよなら銀河鉄道999 -アンドロメダ終着駅-', 'author': '松本零士', 'year': '1981', 'company': '東映動画' },
    { 'id': 33, 'title': '銀河鉄道999 エターナル・ファンタジー', 'author': '松本零士', 'year': '1998', 'company': '東映動画' },
    { 'id': 34, 'title': '銀河鉄道999 星空はタイムマシーン', 'author': '松本零士', 'year': '2007', 'company': '東映アニメーション' },
    { 'id': 35, 'title': '銀の匙 Silver Spoon', 'author': '荒川弘', 'year': '2013', 'company': 'A-1 Pictures' },
    { 'id': 36, 'title': '紅の豚', 'author': '宮崎駿', 'year': '1992', 'company': 'スタジオジブリ' },
    { 'id': 37, 'title': 'クレヨンしんちゃん', 'author': '臼井儀人', 'year': '1992', 'company': 'シンエイ動画' },
    { 'id': 38, 'title': 'ゲゲゲの鬼太郎', 'author': '水木しげる', 'year': '2007', 'company': '東映アニメーション' },
    { 'id': 39, 'title': 'ケシカスくん', 'author': '村瀬範行', 'year': '2010', 'company': '小学館ミュージック&デジタル エンタテイメント' },
    { 'id': 40, 'title': '結界師', 'author': '田辺イエロウ', 'year': '2006', 'company': 'サンライズ' },
    { 'id': 41, 'title': '獣の奏者 エリン', 'author': '上橋菜穂子', 'year': '2009', 'company': 'Production I.Gトランス・アーツ' },
    { 'id': 42, 'title': 'ケロロ軍曹', 'author': '吉崎観音', 'year': '2004', 'company': 'サンライズ' },
    { 'id': 43, 'title': '甲虫王者ムシキング 森の民の伝説', 'author': 'セガ', 'year': '2005', 'company': 'トムス・エンタテインメント' },
    { 'id': 44, 'title': 'コードギアス 反逆のルルーシュ', 'author': '大河内一楼谷口悟朗', 'year': '2006', 'company': 'サンライズ' },
    { 'id': 45, 'title': 'コードギアス 反逆のルルーシュR2', 'author': '大河内一楼谷口悟朗', 'year': '2008', 'company': 'サンライズ' },
    { 'id': 46, 'title': 'コジコジ', 'author': 'さくらももこ', 'year': '1997', 'company': '日本アニメーション' },
    { 'id': 47, 'title': 'こちら葛飾区亀有公園前派出所', 'author': '秋本治', 'year': '1996', 'company': 'ぎゃろっぷ' },
    { 'id': 48, 'title': '小林さんちのメイドラゴン', 'author': 'クール教信者', 'year': '2017', 'company': '京都アニメーション' },
    { 'id': 49, 'title': '小林さんちのメイドラゴンS', 'author': 'クール教信者', 'year': '2021', 'company': '京都アニメーション' },
    { 'id': 50, 'title': '小林さんちのメイドラゴン さみしがりやの竜', 'author': 'クール教信者', 'year': '2025', 'company': '京都アニメーション' },
    { 'id': 51, 'title': 'コボちゃん', 'author': '植田まさし', 'year': '1992', 'company': 'メルヘン社' },
    { 'id': 52, 'title': '金色のガッシュベル!!', 'author': '雷句誠', 'year': '2003', 'company': '東映アニメーション' },
    { 'id': 53, 'title': 'PSYCHO-PASS サイコパス', 'author': '虚淵玄', 'year': '2012', 'company': 'Production I.G' },
    { 'id': 54, 'title': 'サザエさん', 'author': '長谷川町子', 'year': '1969', 'company': 'エイケン' },
    { 'id': 55, 'title': 'ささやくように恋を唄う', 'author': '竹嶋えく', 'year': '2024', 'company': '横浜アニメーションラボクラウドハーツ' },
    { 'id': 56, 'title': 'サマーウォーズ', 'author': '', 'year': '2009', 'company': 'マッドハウス' },
    { 'id': 57, 'title': 'GJ8マン', 'author': 'さくらももこ', 'year': '2016', 'company': '株式会社ライトエアー' },
    { 'id': 58, 'title': 'JOCHUM', 'author': 'サンリオ', 'year': '2024', 'company': 'ファンワークス' },
    { 'id': 59, 'title': 'しかのこのこのここしたんたん', 'author': 'おしおしお', 'year': '2024', 'company': 'WIT STUDIO' },
    { 'id': 60, 'title': 'CITY THE ANIMATION', 'author': 'あらゐけいいち', 'year': '2025', 'company': '京都アニメーション' },
    { 'id': 61, 'title': '邪神ちゃんドロップキック', 'author': 'ユキヲ', 'year': '2018', 'company': 'ノーマッド' },
    { 'id': 62, 'title': "邪神ちゃんドロップキック'", 'author': 'ユキヲ', 'year': '2020', 'company': 'ノーマッド' },
    { 'id': 63, 'title': '邪神ちゃんドロップキックX', 'author': 'ユキヲ', 'year': '2022', 'company': 'ノーマッド' },
    { 'id': 64, 'title': '邪神ちゃんドロップキック【世紀末編】', 'author': 'ユキヲ', 'year': '2023', 'company': 'マカリア' },
    { 'id': 65, 'title': 'ジャム・ザ・ハウスネイル', 'author': '', 'year': '1996', 'company': '野村辰寿' },
    { 'id': 66, 'title': '終末トレインどこへいく？', 'author': 'apogeego', 'year': '2024', 'company': 'EMTスクエアード' },
    { 'id': 67, 'title': '小市民シリーズ', 'author': '米澤穂信', 'year': '2024', 'company': 'ラパントラック' },
    { 'id': 68, 'title': 'ジョジョの奇妙な冒険', 'author': '荒木飛呂彦', 'year': '2012', 'company': 'david production' },
    { 'id': 69, 'title': 'ジョジョの奇妙な冒険 スターダストクルセイダース', 'author': '荒木飛呂彦', 'year': '2014', 'company': 'david production' },
    { 'id': 70, 'title': 'ジョジョの奇妙な冒険 ダイヤモンドは砕けない', 'author': '荒木飛呂彦', 'year': '2016', 'company': 'david production' },
    { 'id': 71, 'title': 'ジョジョの奇妙な冒険 黄金の風', 'author': '荒木飛呂彦', 'year': '2018', 'company': 'david production' },
    { 'id': 72, 'title': 'ジョジョの奇妙な冒険', 'author': '荒木飛呂彦', 'year': '1993', 'company': 'A.P.P.P.' },
    { 'id': 73, 'title': 'シルベスター&トゥイーティー ミステリー', 'author': '', 'year': '1998', 'company': 'Warner Bros. Animation' },
    { 'id': 74, 'title': 'スキマの国のポルタ', 'author': '荒井良二', 'year': '2005', 'company': '和田敏克ピー・アール・オー' },
    { 'id': 75, 'title': 'SKET DANCE', 'author': '篠原健太', 'year': '2011', 'company': 'タツノコプロ' },
    { 'id': 76, 'title': '涼宮ハルヒの憂鬱', 'author': '谷川流', 'year': '2006', 'company': '京都アニメーション' },
    { 'id': 77, 'title': '涼宮ハルヒの消失', 'author': '谷川流', 'year': '2010', 'company': '京都アニメーション' },
    { 'id': 78, 'title': 'すなあそび', 'author': '', 'year': '1995', 'company': '飯面雅子' },
    { 'id': 79, 'title': 'セクシーコマンドー外伝 すごいよ!!マサルさん', 'author': 'うすた京介', 'year': '1998', 'company': 'マジックバス' },
    { 'id': 80, 'title': '絶体絶命でんぢゃらすじーさん', 'author': '曽山一寿', 'year': '2004', 'company': 'スタジオ雲雀' },
    { 'id': 81, 'title': 'ぜんまいざむらい', 'author': 'm&k', 'year': '2006', 'company': 'A-1 Picturesノーサイド' },
    { 'id': 82, 'title': '葬送のフリーレン', 'author': '山田鐘人アベツカサ', 'year': '2023', 'company': 'マッドハウス' },
    { 'id': 83, 'title': 'それいけ!アンパンマン', 'author': 'やなせたかし', 'year': '1988', 'company': 'トムス・エンタテインメント' },
    { 'id': 84, 'title': 'ダイヤのA', 'author': '寺嶋裕二', 'year': '2013', 'company': 'MADHOUSEProduction I.G' },
    { 'id': 85, 'title': '大好き!ねんどママ', 'author': '', 'year': '1994', 'company': 'ヒダオサム' },
    { 'id': 86, 'title': 'タンタンの冒険', 'author': 'Hergé', 'year': '1998', 'company': 'NelvanaEllipse' },
    { 'id': 87, 'title': '団地ともお', 'author': '小田扉', 'year': '2013', 'company': '小学館ミュージック&デジタル エンタテイメント' },
    { 'id': 88, 'title': 'チキップダンサーズ', 'author': 'サンエックス', 'year': '2021', 'company': 'ファンワークス' },
    { 'id': 89, 'title': 'チックンタック', 'author': '', 'year': '1999', 'company': '鈴木伸一' },
    { 'id': 90, 'title': 'ちびまる子ちゃん', 'author': 'さくらももこ', 'year': '1990', 'company': '日本アニメーション' },
    { 'id': 91, 'title': 'ちびまる子ちゃん わたしの好きな歌', 'author': 'さくらももこ', 'year': '1992', 'company': '亜細亜堂' },
    { 'id': 92, 'title': 'ちびまる子ちゃん イタリアから来た少年', 'author': 'さくらももこ', 'year': '2015', 'company': '日本アニメーション' },
    { 'id': 93, 'title': 'CHOPPER’s', 'author': '尾田栄一郎', 'year': '2026', 'company': 'ダンデライオンアニメーションスタジオスタジオエイトカラーズ' },
    { 'id': 94, 'title': 'CHOPPER’s Journey', 'author': '尾田栄一郎', 'year': '2026', 'company': 'maxillaPlusboku Design' },
    { 'id': 95, 'title': 'デジモンアドベンチャー', 'author': '本郷あきよし', 'year': '1999', 'company': '東映アニメーション' },
    { 'id': 96, 'title': 'デジモンアドベンチャー ぼくらのウォーゲーム!', 'author': '本郷あきよし', 'year': '2000', 'company': '東映アニメーション' },
    { 'id': 97, 'title': 'DEATH NOTE', 'author': '大場つぐみ小畑健', 'year': '2006', 'company': 'マッドハウス' },
    { 'id': 98, 'title': '天空の城ラピュタ', 'author': '宮崎駿', 'year': '1986', 'company': 'スタジオジブリ' },
    { 'id': 99, 'title': '天元突破グレンラガン', 'author': 'GAINAX', 'year': '2007', 'company': 'GAINAX' },
    { 'id': 100, 'title': '電光超特急ヒカリアン', 'author': 'すずきいおり', 'year': '2002', 'company': '東京キッズ' },
    { 'id': 101, 'title': '電脳コイル', 'author': '磯光雄', 'year': '2007', 'company': 'マッドハウス' },
    { 'id': 102, 'title': '天までとどけ', 'author': '', 'year': '1993', 'company': 'マガリ事務所' },
    { 'id': 103, 'title': '時をかける少女', 'author': '筒井康隆', 'year': '2006', 'company': 'マッドハウス' },
    { 'id': 104, 'title': 'Dr.スランプ アラレちゃん', 'author': '鳥山明', 'year': '1981', 'company': '東映動画' },
    { 'id': 105, 'title': 'となりのトトロ', 'author': '宮崎駿', 'year': '1988', 'company': 'スタジオジブリ' },
    { 'id': 106, 'title': 'ドラえもん', 'author': '藤本弘', 'year': '1979', 'company': 'シンエイ動画' },
    { 'id': 107, 'title': 'トリコ', 'author': '島袋光年', 'year': '2011', 'company': '東映アニメーション' },
    { 'id': 108, 'title': '謎解きはディナーのあとで', 'author': '東川篤哉', 'year': '2025', 'company': 'マッドハウス' },
    { 'id': 109, 'title': 'ナッチョとポム', 'author': '', 'year': '2002', 'company': 'スタジオ・ユサキ' },
    { 'id': 110, 'title': '日常', 'author': 'あらゐけいいち', 'year': '2011', 'company': '京都アニメーション' },
    { 'id': 111, 'title': '忍たま乱太郎', 'author': '尼子騒兵衛', 'year': '1993', 'company': '亜細亜堂学研' },
    { 'id': 112, 'title': 'のんのんびより', 'author': 'あっと', 'year': '2013', 'company': 'SILVER LINK.' },
    { 'id': 113, 'title': 'のんのんびより りぴーと', 'author': 'あっと', 'year': '2015', 'company': 'SILVER LINK.' },
    { 'id': 114, 'title': 'のんのんびより のんすとっぷ', 'author': 'あっと', 'year': '2021', 'company': 'SILVER LINK.' },
    { 'id': 115, 'title': 'のんのんびより ばけーしょん', 'author': 'あっと', 'year': '2018', 'company': 'SILVER LINK.' },
    { 'id': 116, 'title': 'ハイスクール！奇面組', 'author': '新沢基栄', 'year': '2026', 'company': 'アニメーションスタジオ・セブン' },
    { 'id': 117, 'title': 'バクマン。', 'author': '大場つぐみ小畑健', 'year': '2010', 'company': 'J.C.STAFF' },
    { 'id': 118, 'title': '化物語', 'author': '西尾維新', 'year': '2009', 'company': 'シャフト' },
    { 'id': 119, 'title': '偽物語', 'author': '西尾維新', 'year': '2012', 'company': 'シャフト' },
    { 'id': 120, 'title': '〈物語〉シリーズ オフ&モンスターシーズン', 'author': '西尾維新', 'year': '2024', 'company': 'シャフト' },
    { 'id': 121, 'title': '傷物語 -こよみヴァンプ-', 'author': '西尾維新', 'year': '2024', 'company': 'シャフト' },
    { 'id': 122, 'title': 'バケモノの子', 'author': '細田守', 'year': '2015', 'company': 'スタジオ地図' },
    { 'id': 123, 'title': 'はたらく細胞', 'author': '清水茜', 'year': '2018', 'company': 'david production' },
    { 'id': 124, 'title': 'はたらく細胞!!', 'author': '清水茜', 'year': '2021', 'company': 'david production' },
    { 'id': 125, 'title': 'PUPPET SUNSUN', 'author': 'パペットスンスン', 'year': '2025', 'company': '' },
    { 'id': 126, 'title': 'ひきこまり吸血姫の悶々', 'author': '小林湖底', 'year': '2023', 'company': 'project No.9' },
    { 'id': 127, 'title': 'ひぐらしのなく頃に', 'author': '竜騎士07/07th Expansion', 'year': '2006', 'company': 'スタジオディーン' },
    { 'id': 128, 'title': 'ひつじのショーン', 'author': 'Nick Park', 'year': '2007', 'company': 'アードマン・アニメーションズ' },
    { 'id': 129, 'title': 'ビップとバップ', 'author': '', 'year': '2001', 'company': '和田敏克' },
    { 'id': 130, 'title': '火の鳥', 'author': '手塚治虫', 'year': '2004', 'company': '手塚プロダクション' },
    { 'id': 131, 'title': '日々は過ぎれど飯うまし', 'author': 'team apa', 'year': '2025', 'company': 'P.A.WORKS' },
    { 'id': 132, 'title': '180秒で君の耳を幸せにできるか？', 'author': 'RaRo', 'year': '2021', 'company': 'INDIVISIONエカチエピルカ' },
    { 'id': 133, 'title': '氷菓', 'author': '米澤穂信', 'year': '2012', 'company': '京都アニメーション' },
    { 'id': 134, 'title': 'プリンプリン物語', 'author': '石山透', 'year': '1974', 'company': 'NHK総合テレビジョン' },
    { 'id': 135, 'title': 'ふるさと再生 日本の昔話', 'author': '', 'year': '2012', 'company': 'トマソン' },
    { 'id': 136, 'title': '平成狸合戦ぽんぽこ', 'author': '高畑勲', 'year': '1994', 'company': 'スタジオジブリ' },
    { 'id': 137, 'title': 'ペンギンの問題', 'author': '永井ゆうじ', 'year': '2008', 'company': '小学館ミュージック&デジタル エンタテイメント' },
    { 'id': 138, 'title': '僕のヒーローアカデミア', 'author': '堀越耕平', 'year': '2016', 'company': 'ボンズ' },
    { 'id': 139, 'title': '星屑テレパス', 'author': '大熊らすこ', 'year': '2023', 'company': 'Studio五組' },
    { 'id': 140, 'title': '星のカービィ', 'author': '桜井政博', 'year': '2001', 'company': 'スタジオ・ザイン' },
    { 'id': 141, 'title': '火垂るの墓', 'author': '野坂昭如', 'year': '1988', 'company': 'スタジオジブリ' },
    { 'id': 142, 'title': 'ぼっち・ざ・ろっく！', 'author': 'はまじあき', 'year': '2022', 'company': 'CloverWorks' },
    { 'id': 143, 'title': 'ポプテピピック', 'author': '大川ぶくぶ', 'year': '2018', 'company': '神風動画' },
    { 'id': 144, 'title': 'ポペティ', 'author': '', 'year': '2005', 'company': 'R.AmadorC.Schouwenaar' },
    { 'id': 145, 'title': 'ボボボーボ・ボーボボ', 'author': '澤井啓夫', 'year': '2003', 'company': '東映アニメーション' },
    { 'id': 146, 'title': 'ぽんのみち', 'author': 'IIS-P', 'year': '2024', 'company': 'OLM TEAM INOUE' },
    { 'id': 147, 'title': '魔女の宅急便', 'author': '角野栄子', 'year': '1989', 'company': 'スタジオジブリ' },
    { 'id': 148, 'title': 'まちカドまぞく', 'author': '伊藤いづも', 'year': '2019', 'company': 'J.C.STAFF' },
    { 'id': 149, 'title': 'まちカドまぞく ２丁目', 'author': '伊藤いづも', 'year': '2022', 'company': 'J.C.STAFF' },
    { 'id': 150, 'title': "魔法少女リリカルなのは A's", 'author': '都築真紀 / ivory', 'year': '2005', 'company': 'セブン・アークス' },
    { 'id': 151, 'title': '魔法少女リリカルなのは StrikerS', 'author': '都築真紀 / ivory', 'year': '2007', 'company': 'セブン・アークス' },
    { 'id': 152, 'title': '魔法少女リリカルなのは', 'author': '都築真紀 / ivory', 'year': '2004', 'company': 'セブン・アークス' },
    { 'id': 153, 'title': 'マリー&ガリー', 'author': '東堂いづみ', 'year': '2009', 'company': '東映アニメーション' },
    { 'id': 154, 'title': 'マリー&ガリーVer2.0', 'author': '東堂いづみ', 'year': '2010', 'company': '東映アニメーション' },
    { 'id': 155, 'title': 'まんが日本昔ばなし', 'author': '', 'year': '1975', 'company': '毎日放送愛企画センターグループ・タック' },
    { 'id': 156, 'title': '宮河家の空腹', 'author': '美水かがみ', 'year': '2013', 'company': 'Ordetエンカレッジフィルムズ' },
    { 'id': 157, 'title': '未来のミライ', 'author': '細田守', 'year': '2018', 'company': 'スタジオ地図' },
    { 'id': 158, 'title': 'メジャー 第1シリーズ', 'author': '満田拓也', 'year': '2004', 'company': 'SynergySP' },
    { 'id': 159, 'title': 'メジャー 第1シリーズ', 'author': '満田拓也', 'year': '2004', 'company': 'SynergySP' },
    { 'id': 160, 'title': 'メジャー 第2シリーズ', 'author': '満田拓也', 'year': '2005', 'company': 'SynergySP' },
    { 'id': 161, 'title': 'メジャー 第3シリーズ', 'author': '満田拓也', 'year': '2007', 'company': 'SynergySP' },
    { 'id': 162, 'title': 'メジャー 第4シリーズ', 'author': '満田拓也', 'year': '2008', 'company': 'SynergySP' },
    { 'id': 163, 'title': 'メジャー 第5シリーズ', 'author': '満田拓也', 'year': '2009', 'company': 'SynergySP' },
    { 'id': 164, 'title': 'メジャー 第6シリーズ', 'author': '満田拓也', 'year': '2010', 'company': 'SynergySP' },
    { 'id': 165, 'title': 'めだかボックス', 'author': '西尾維新暁月あきら', 'year': '2012', 'company': 'GAINAX' },
    { 'id': 166, 'title': 'mono', 'author': 'あfろ', 'year': '2025', 'company': 'ソワネ' },
    { 'id': 167, 'title': 'もめんたりー・リリィ', 'author': 'GoHands × 松竹', 'year': '2025', 'company': 'GoHands' },
    { 'id': 168, 'title': 'ももんがぁモン', 'author': '', 'year': '2005', 'company': 'かわいとしひこ' },
    { 'id': 169, 'title': '森のレシオ', 'author': '', 'year': '2010', 'company': '村田朋泰' },
    { 'id': 170, 'title': '焼きたて!!ジャぱん', 'author': '橋口たかし', 'year': '2004', 'company': 'サンライズ' },
    { 'id': 171, 'title': '約束のネバーランド', 'author': '白井カイウ出水ぽすか', 'year': '2019', 'company': 'CloverWorks' },
    { 'id': 172, 'title': 'ヤマノススメ', 'author': 'しろ', 'year': '2013', 'company': 'エイトビット' },
    { 'id': 173, 'title': 'ヤマノススメ セカンドシーズン', 'author': 'しろ', 'year': '2014', 'company': 'エイトビット' },
    { 'id': 174, 'title': 'ヤマノススメ サードシーズン', 'author': 'しろ', 'year': '2018', 'company': 'エイトビット' },
    { 'id': 175, 'title': 'ヤマノススメ Next Summit', 'author': 'しろ', 'year': '2022', 'company': 'エイトビット' },
    { 'id': 176, 'title': 'ゆゆ式', 'author': '三上小又', 'year': '2013', 'company': 'キネマシトラス' },
    { 'id': 177, 'title': 'ゆるキャン△', 'author': 'あfろ', 'year': '2018', 'company': 'C-Station' },
    { 'id': 178, 'title': 'ゆるキャン△ SEASON2', 'author': 'あfろ', 'year': '2021', 'company': 'C-Station' },
    { 'id': 179, 'title': 'ゆるキャン△ SEASON3', 'author': 'あfろ', 'year': '2024', 'company': 'エイトビット' },
    { 'id': 180, 'title': 'へやキャン△', 'author': 'あfろ', 'year': '2020', 'company': 'C-Station' },
    { 'id': 181, 'title': 'ゆるゆり', 'author': 'なもり', 'year': '2011', 'company': '動画工房' },
    { 'id': 182, 'title': 'ゆるゆり なちゅやちゅみ!+', 'author': 'なもり', 'year': '2015', 'company': 'TYOアニメーションズ' },
    { 'id': 183, 'title': 'ゆるゆり♪♪♪', 'author': 'なもり', 'year': '2012', 'company': '動画工房' },
    { 'id': 184, 'title': 'みにゆり', 'author': 'なもり', 'year': '2019', 'company': 'DMM.futureworksダブトゥーンスタジオ' },
    { 'id': 185, 'title': '弱虫クルッパー', 'author': 'Joe RubyKen Spears', 'year': '1970', 'company': 'Hanna-Barbera' },
    { 'id': 186, 'title': 'らき☆すた', 'author': '美水かがみ', 'year': '2007', 'company': '京都アニメーション' },
    { 'id': 187, 'title': 'らんま\\(\x0crac{1}{2}\\)', 'author': '高橋留美子', 'year': '2024', 'company': 'MAPPA' },
    { 'id': 188, 'title': 'リコリス・リコイル', 'author': 'Spider Lily', 'year': '2022', 'company': 'A-1 Pictures' },
    { 'id': 189, 'title': 'リセス 〜ぼくらの休み時間〜', 'author': 'Paul GermainJoe Ansolabehere', 'year': '2000', 'company': 'ディズニー・テレビジョンアニメーション' },
    { 'id': 190, 'title': 'ルパン三世 PART1', 'author': 'モンキー・パンチ', 'year': '1971', 'company': '東京ムービー' },
    { 'id': 191, 'title': 'ルパン三世 PART2', 'author': 'モンキー・パンチ', 'year': '1977', 'company': '東京ムービー' },
    { 'id': 192, 'title': 'ルパン三世 PARTIII', 'author': 'モンキー・パンチ', 'year': '1984', 'company': '東京ムービー新社' },
    { 'id': 193, 'title': 'ロボットパルタ', 'author': '', 'year': '1994', 'company': '保田克史' },
    { 'id': 194, 'title': 'WORKING!!', 'author': '高津カリノ', 'year': '2010', 'company': 'A-1 Pictures' },
    { 'id': 195, 'title': "WORKING'!!", 'author': '高津カリノ', 'year': '2011', 'company': 'A-1 Pictures' },
    { 'id': 196, 'title': 'WORKING!!!', 'author': '高津カリノ', 'year': '2015', 'company': 'A-1 Pictures' },
    { 'id': 197, 'title': '私に天使が舞い降りた！', 'author': '椋木ななつ', 'year': '2019', 'company': '動画工房' },
    { 'id': 198, 'title': '私の推しは悪役令嬢。', 'author': 'いのり。', 'year': '2023', 'company': 'プラチナビジョン' },
    { 'id': 199, 'title': '私の百合はお仕事です！', 'author': '未幡', 'year': '2023', 'company': 'パッショーネスタジオリングス' },
    { 'id': 200, 'title': 'ONE PIECE', 'author': '尾田栄一郎', 'year': '1999', 'company': '東映アニメーション' }
];

</script>

<template>
    <Header />
    <div>
        <VueGoodTable :columns="columns" :rows="rows" />
    </div>
    <Footer />
</template>