<script setup lang="ts">
import { VueGoodTable } from 'vue-good-table-next';
import 'vue-good-table-next/dist/vue-good-table-next.css';

import Header from '~/components/Header.vue';
import Footer from '~/components/Footer.vue';

const columns = [
    { label: "タイトル", field: "title" },
    { label: "原作", field: "author" },
    { label: "出版年", field: "year" },
    { label: "出版社", field: "company" },
];

const rows = [
    { 'id': 1, 'title': 'Helvetica Standard', 'author': 'あらゐけいいち', 'year': '2011', 'company': '角川コミックス・エース' },
    { 'id': 2, 'title': 'Helvetica Standard\u3000絵', 'author': 'あらゐけいいち', 'year': '2014', 'company': '角川コミックス・エース' },
    { 'id': 3, 'title': 'アイマスどうでしょう\u3000試験に出るどうでしょう', 'author': 'タカ', 'year': '2024', 'company': '桃京武戯夜' },
    { 'id': 4, 'title': 'あずまんが大王（１）', 'author': 'あずまきよひこ', 'year': '2000', 'company': '電撃コミックスEX' },
    { 'id': 5, 'title': 'あずまんが大王（２）', 'author': 'あずまきよひこ', 'year': '2000', 'company': '電撃コミックスEX' },
    { 'id': 6, 'title': 'あずまんが大王（３）', 'author': 'あずまきよひこ', 'year': '2001', 'company': '電撃コミックスEX' },
    { 'id': 7, 'title': 'あずまんが大王（４）', 'author': 'あずまきよひこ', 'year': '2002', 'company': '電撃コミックスEX' },
    { 'id': 8, 'title': '雨宮さん（１）', 'author': 'あらゐけいいち', 'year': '2022', 'company': '少年サンデーコミックス' },
    { 'id': 9, 'title': '苺ましまろ（１）', 'author': 'ばらスィー', 'year': '2003', 'company': '電撃コミックス' },
    { 'id': 10, 'title': '苺ましまろ（２）', 'author': 'ばらスィー', 'year': '2003', 'company': '電撃コミックス' },
    { 'id': 11, 'title': '苺ましまろ（３）', 'author': 'ばらスィー', 'year': '2004', 'company': '電撃コミックス' },
    { 'id': 12, 'title': '苺ましまろ（４）', 'author': 'ばらスィー', 'year': '2005', 'company': '電撃コミックス' },
    { 'id': 13, 'title': '苺ましまろ（５）', 'author': 'ばらスィー', 'year': '2007', 'company': '電撃コミックス' },
    { 'id': 14, 'title': '宇宙ファラオ☆パトラちゃん', 'author': 'ユキヲ', 'year': '2016', 'company': 'まんがタイムコミックス' },
    { 'id': 15, 'title': 'おまもりんごさん', 'author': 'ms/hirahira.net', 'year': '2010', 'company': 'まんがタイムKRコミックス' },
    { 'id': 16, 'title': 'カメラ、はじめてもいいですか？（１）', 'author': 'しろ', 'year': '2020', 'company': 'ヤングキングコミックス' },
    { 'id': 17, 'title': 'カメラ、はじめてもいいですか？（２）', 'author': 'しろ', 'year': '2021', 'company': 'ヤングキングコミックス' },
    { 'id': 18, 'title': 'カメラ、はじめてもいいですか？（３）', 'author': 'しろ', 'year': '2022', 'company': 'ヤングキングコミックス' },
    { 'id': 19, 'title': '岸辺露伴は動かない', 'author': '荒木飛呂彦', 'year': '2013', 'company': 'ジャンプ・コミックス' },
    { 'id': 20, 'title': '岸辺露伴は動かない（２）', 'author': '荒木飛呂彦', 'year': '2018', 'company': 'ジャンプコミックス' },
    { 'id': 21, 'title': '岸辺露伴は動かない（３）', 'author': '荒木飛呂彦', 'year': '2025', 'company': 'ジャンプコミックス' },
    { 'id': 22, 'title': 'けいおん！（１）', 'author': 'かきふらい', 'year': '2008', 'company': 'まんがタイムKRコミックス' },
    { 'id': 23, 'title': 'けいおん！（２）', 'author': 'かきふらい', 'year': '2009', 'company': 'まんがタイムKRコミックス' },
    { 'id': 24, 'title': 'けいおん！（３）', 'author': 'かきふらい', 'year': '2010', 'company': 'まんがタイムKRコミックス' },
    { 'id': 25, 'title': 'けいおん！（４）', 'author': 'かきふらい', 'year': '2010', 'company': 'まんがタイムKRコミックス' },
    { 'id': 26, 'title': '現代魔女の就職事情（１）', 'author': 'はま and 相沢沙呼', 'year': '2015', 'company': '電撃コミックスNEXT' },
    { 'id': 27, 'title': '現代魔女の就職事情（２）', 'author': 'はま and 相沢沙呼', 'year': '2016', 'company': '電撃コミックスNEXT' },
    { 'id': 28, 'title': '現代魔女の就職事情（４）', 'author': 'はま and 相沢沙呼', 'year': '2017', 'company': '電撃コミックスNEXT' },
    { 'id': 29, 'title': 'ごっどちゃんず（１）', 'author': 'ユキヲ', 'year': '2018', 'company': 'MFCキューンシリーズ' },
    { 'id': 30, 'title': 'ごっどちゃんず（２）', 'author': 'ユキヲ', 'year': '2020', 'company': 'MFCキューンシリーズ' },
    { 'id': 31, 'title': '小林さんちのメイドラゴン（８）', 'author': 'クール教信者', 'year': '2019', 'company': '月刊アクション' },
    { 'id': 32, 'title': '小林さんちのメイドラゴン（９）', 'author': 'クール教信者', 'year': '2019', 'company': '月刊アクション' },
    { 'id': 33, 'title': '小林さんちのメイドラゴン（１２）', 'author': 'クール教信者', 'year': '2022', 'company': '月刊アクション' },
    { 'id': 34, 'title': '小林さんちのメイドラゴン\u3000エルマのOL日記（３）', 'author': 'カザマアヤミ and クール教信者', 'year': '2019', 'company': '月刊アクション' },
    { 'id': 35, 'title': '小林さんちのメイドラゴン\u3000エルマのOL日記（４）', 'author': 'カザマアヤミ and クール教信者', 'year': '2020', 'company': '月刊アクション' },
    { 'id': 36, 'title': '小林さんちのメイドラゴン\u3000公式ファンブック\u3000まるごとカンナ', 'author': 'クール教信者 et al.', 'year': '2025', 'company': '月刊アクション' },
    { 'id': 37, 'title': '桜Trickアンソロジーコミック（１）', 'author': 'アンソロジー', 'year': '2014', 'company': 'まんがタイムKRコミックス' },
    { 'id': 38, 'title': 'サマーウォーズ\u3000公式コミックアンソロジー', 'author': 'アンソロジー', 'year': '2010', 'company': '角川コミックス・エース' },
    { 'id': 39, 'title': '邪神ちゃんドロップキック（１）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 40, 'title': '邪神ちゃんドロップキック（２）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 41, 'title': '邪神ちゃんドロップキック（３）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 42, 'title': '邪神ちゃんドロップキック（４）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 43, 'title': '邪神ちゃんドロップキック（５）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 44, 'title': '邪神ちゃんドロップキック（６）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 45, 'title': '邪神ちゃんドロップキック（７）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 46, 'title': '邪神ちゃんドロップキック（８）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 47, 'title': '邪神ちゃんドロップキック（９）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 48, 'title': '邪神ちゃんドロップキック（１０）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 49, 'title': '邪神ちゃんドロップキック（１１）', 'author': 'ユキヲ', 'year': '2018', 'company': 'メテオ・コミックス' },
    { 'id': 50, 'title': '邪神ちゃんドロップキック（１２）', 'author': 'ユキヲ', 'year': '2019', 'company': 'メテオ・コミックス' },
    { 'id': 51, 'title': '邪神ちゃんドロップキック（１３）', 'author': 'ユキヲ', 'year': '2019', 'company': 'メテオ・コミックス' },
    { 'id': 52, 'title': '邪神ちゃんドロップキック（１４）', 'author': 'ユキヲ', 'year': '2020', 'company': 'メテオ・コミックス' },
    { 'id': 53, 'title': '邪神ちゃんドロップキック（１５）', 'author': 'ユキヲ', 'year': '2020', 'company': 'メテオ・コミックス' },
    { 'id': 54, 'title': '邪神ちゃんドロップキック（１６）', 'author': 'ユキヲ', 'year': '2020', 'company': 'メテオ・コミックス' },
    { 'id': 55, 'title': '邪神ちゃんドロップキック（１７）', 'author': 'ユキヲ', 'year': '2021', 'company': 'メテオ・コミックス' },
    { 'id': 56, 'title': '邪神ちゃんドロップキック（１８）', 'author': 'ユキヲ', 'year': '2021', 'company': 'メテオ・コミックス' },
    { 'id': 57, 'title': '邪神ちゃんドロップキック（１９）', 'author': 'ユキヲ', 'year': '2022', 'company': 'メテオ・コミックス' },
    { 'id': 58, 'title': '邪神ちゃんドロップキック（２０）', 'author': 'ユキヲ', 'year': '2022', 'company': 'メテオ・コミックス' },
    { 'id': 59, 'title': '邪神ちゃんドロップキック（２１）', 'author': 'ユキヲ', 'year': '2023', 'company': 'メテオ・コミックス' },
    { 'id': 60, 'title': '邪神ちゃんドロップキック（２２）', 'author': 'ユキヲ', 'year': '2023', 'company': 'メテオ・コミックス' },
    { 'id': 61, 'title': '邪神ちゃんドロップキック（２３）', 'author': 'ユキヲ', 'year': '2024', 'company': 'メテオ・コミックス' },
    { 'id': 62, 'title': '邪神ちゃんドロップキック（２４）', 'author': 'ユキヲ', 'year': '2024', 'company': 'メテオ・コミックス' },
    { 'id': 63, 'title': 'しょうこセンセイ！（１）', 'author': 'なじみ', 'year': '2019', 'company': 'まんがタイムKRコミックス' },
    { 'id': 64, 'title': '少女終末旅行（１）', 'author': 'つくみず', 'year': '2014', 'company': 'バンチ・コミックス' },
    { 'id': 65, 'title': '白雪姫と黒タイツ（１）', 'author': '御影石材', 'year': '2017', 'company': 'みんなのコミック' },
    { 'id': 66, 'title': '新装版\u3000こあくまメレンゲ', 'author': 'あっと', 'year': '2014', 'company': 'MFコミックス\u3000アライブシリーズ' },
    { 'id': 67, 'title': '水曜どうでしょう〜大泉洋のホラ話〜（１）', 'author': '星野倖一郎 and 大泉洋', 'year': '2020', 'company': '少年チャンピオン・コミックス' },
    { 'id': 68, 'title': '永沢君', 'author': 'さくらももこ', 'year': '2019', 'company': 'MOMOKO BOMBER COMICS' },
    { 'id': 69, 'title': 'のんのんびより（１）', 'author': 'あっと', 'year': '2010', 'company': 'MFコミックス\u3000アライブシリーズ' },
    { 'id': 70, 'title': 'のんのんびより（２）', 'author': 'あっと', 'year': '2010', 'company': 'MFコミックス\u3000アライブシリーズ' },
    { 'id': 71, 'title': 'のんのんびより（３）', 'author': 'あっと', 'year': '2011', 'company': 'MFコミックス\u3000アライブシリーズ' },
    { 'id': 72, 'title': 'のんのんびより（１５）', 'author': 'あっと', 'year': '2020', 'company': 'MFコミックス\u3000アライブシリーズ' },
    { 'id': 73, 'title': 'はたらく細胞おくすり（１）', 'author': '久似良，割田コマ and 清水茜', 'year': '2024', 'company': 'シリウスKC' },
    { 'id': 74, 'title': 'はたらく細胞おくすり（２）', 'author': '久似良，割田コマ and 清水茜', 'year': '2024', 'company': 'シリウスKC' },
    { 'id': 75, 'title': 'はたらく細胞おくすり（３）', 'author': '久似良，割田コマ and 清水茜', 'year': '2024', 'company': 'シリウスKC' },
    { 'id': 76, 'title': 'ひだまりスケッチ\u3000ストーリーアンソロジーコミック', 'author': 'アンソロジー', 'year': '2012', 'company': 'まんがタイムKRコミックス' },
    { 'id': 77, 'title': '日々是好日（１）', 'author': '粕家梅庵', 'year': '2024', 'company': '梅プロダクション' },
    { 'id': 78, 'title': '日々は過ぎれど飯うまし（１）', 'author': 'Quro and あっと', 'year': '2025', 'company': 'MFコミックス アライブ+シリーズ' },
    { 'id': 79, 'title': '日々は過ぎれど飯うまし（２）', 'author': 'Quro and あっと', 'year': '2026', 'company': 'MFコミックス アライブ+シリーズ' },
    { 'id': 80, 'title': '日々は過ぎれど飯うまし 公式コミックアンソロジー', 'author': 'Quro and あっと', 'year': '2026', 'company': 'MFコミックス アライブ+シリーズ' },
    { 'id': 81, 'title': '宮河家の空腹（１）', 'author': '美水かがみ', 'year': '2012', 'company': '角川コミックス' },
    { 'id': 82, 'title': 'やってやれ幻想郷', 'author': 'あらたとしひら and ZUN', 'year': '2022', 'company': '電撃コミックスEX' },
    { 'id': 83, 'title': 'ヤマノススメ（１４）', 'author': 'しろ', 'year': '2017', 'company': 'アース・スターコミックス' },
    { 'id': 84, 'title': 'ヤマノススメ（２０）', 'author': 'しろ', 'year': '2021', 'company': 'アース・スターコミックス' },
    { 'id': 85, 'title': 'ヤマノススメ（２２）', 'author': 'しろ', 'year': '2022', 'company': 'アース・スターコミックス' },
    { 'id': 86, 'title': 'ヤマノススメ（２５）', 'author': 'しろ', 'year': '2024', 'company': 'アース・スターコミックス' },
    { 'id': 87, 'title': '百合百景', 'author': 'はちこ', 'year': '2017', 'company': 'MFC' },
    { 'id': 88, 'title': 'ゆりゆり', 'author': 'なもり', 'year': '2012', 'company': '百合姫コミックス' },
    { 'id': 89, 'title': '淀屋橋（１）', 'author': '粕家梅庵', 'year': '2024', 'company': '梅プロダクション' },
    { 'id': 90, 'title': 'らき☆すた（１）', 'author': '美水かがみ', 'year': '2005', 'company': '角川コミックス' },
    { 'id': 91, 'title': 'らき☆すた（２）', 'author': '美水かがみ', 'year': '2005', 'company': '角川コミックス' },
    { 'id': 92, 'title': 'らき☆すた（３）', 'author': '美水かがみ', 'year': '2006', 'company': '角川コミックス' },
    { 'id': 93, 'title': 'らき☆すた（４）', 'author': '美水かがみ', 'year': '2007', 'company': '角川コミックス' },
    { 'id': 94, 'title': 'らき☆すた（５）', 'author': '美水かがみ', 'year': '2007', 'company': '角川コミックス' },
    { 'id': 95, 'title': 'らき☆すた（６）', 'author': '美水かがみ', 'year': '2008', 'company': '角川コミックス' },
    { 'id': 96, 'title': 'らき☆すた（７）', 'author': '美水かがみ', 'year': '2009', 'company': '角川コミックス' },
    { 'id': 97, 'title': 'らき☆すた（８）', 'author': '美水かがみ', 'year': '2010', 'company': '角川コミックス' },
    { 'id': 98, 'title': 'らき☆すた コミックアラカルト〜ブリリアント☆すたー〜', 'author': 'アンソロジー', 'year': '2009', 'company': '角川コミックス' },
    { 'id': 99, 'title': 'らき☆すた\u3000コミックアラカルト〜ラッキーたーん〜', 'author': 'アンソロジー', 'year': '2008', 'company': '角川コミックス' },
    { 'id': 100, 'title': 'らき☆すた\u3000コミックアラカルト〜はっぴーストライク！〜', 'author': 'アンソロジー', 'year': '2007', 'company': '角川コミックス' },
    { 'id': 101, 'title': 'らき☆すた\u3000ポケットとらべら〜ず', 'author': 'あかりりゅりゅ羽 and 美水かがみ', 'year': '2008', 'company': '角川コミックス' },
    { 'id': 102, 'title': '√中学生（１）', 'author': 'さくやついたち', 'year': '2012', 'company': 'まんがタイムKRコミックス' },
    { 'id': 103, 'title': 'ろんぐらいだぁす！（１）', 'author': '三宅大志 and LONGRIDERS', 'year': '2013', 'company': 'REXコミックス' },
    { 'id': 104, 'title': 'ろんぐらいだぁす！（２）', 'author': '三宅大志 and LONGRIDERS', 'year': '2013', 'company': 'REXコミックス' },
    { 'id': 105, 'title': '私に天使が舞い降りた！（１３）', 'author': '椋木ななつ', 'year': '2023', 'company': '百合姫コミックス' },
    { 'id': 106, 'title': '私に天使が舞い降りた！（１６）', 'author': '椋木ななつ', 'year': '2025', 'company': '百合姫コミックス' }
];
</script>

<template>
    <Header />
    <p>
        ここでは，私の読んだ漫画について書いていきます．
    </p>
    <div>
        <VueGoodTable :columns="columns" :rows="rows" theme="nocturnal" />
    </div>
    <Footer />
</template>