<script setup lang="ts">
import { VueGoodTable } from 'vue-good-table-next';
import 'vue-good-table-next/dist/vue-good-table-next.css';

import Header from '~/components/Header.vue';
import Footer from '~/components/Footer.vue';

const columns = [
    { label: "タイトル", field: "title" },
    { label: "著者", field: "author" },
    { label: "出版年", field: "year" },
    { label: "ジャンル", field: "type" },
]

const rows = [
    { 'id': 1, 'title': 'A polynomial time version of LLL with deep insertions', 'author': 'Felix Fontein，Michael Schneidery and Urs Wagnerz', 'year': '2018', 'type': '論文' },
    { 'id': 2, 'title': 'Analysis of decreasing squared-sum of Gram–Schmidt lengths for short lattice vectors', 'author': '安田雅哉，横山和弘，下山武司，小暮淳 and 小柴健史', 'year': '2017', 'type': '論文' },
    { 'id': 3, 'title': 'An LLL algorithm with quadratic complexity', 'author': 'Phong Q. Nguyen and Damien Stehle', 'year': '2009', 'type': '論文' },
    { 'id': 4, 'title': 'C++ライブラリEigenのメモ', 'author': 'シ', 'year': '2013', 'type': '技術書' },
    { 'id': 5, 'title': 'Computational Mathematics with SageMath', 'author': 'Paul Zimmermann et al.', 'year': '2019', 'type': '技術書' },
    { 'id': 6, 'title': 'DeepLLLを用いたSVP解読報告', 'author': '山口純平 and 安田雅哉', 'year': '2017', 'type': '論文' },
    { 'id': 7, 'title': 'F4 Algorithm及びSignature Based Algorithmの実装と改良について', 'author': '齋藤大斗', 'year': '2025', 'type': '論文' },
    { 'id': 8, 'title': 'Factoring integers by CVP algorithms', 'author': 'Claus Peter Schnorr', 'year': '2013', 'type': '論文' },
    { 'id': 9, 'title': 'Factoring integers with sublinear resources on a superconducting quantum processor', 'author': 'Bao Yan et al.', 'year': '2022', 'type': '論文' },
    { 'id': 10, 'title': 'Floating-Point LLL Revisited', 'author': 'Phong Q. Nguyen and Damien Stehle', 'year': '2002', 'type': '論文' },
    { 'id': 11, 'title': 'Illustrator Fan for Windows', 'author': '宮川千春++', 'year': '2002', 'type': '技術書' },
    { 'id': 12, 'title': 'Jashihon04', 'author': 'ひなたもも', 'year': '2024', 'type': '同人画集' },
    { 'id': 13, 'title': 'Lattice Basis Reduction', 'author': 'Murray R. Bremner', 'year': '2012', 'type': '数学書' },
    { 'id': 14, 'title': 'Pythonで学ぶはじめてのAIプログラミング', 'author': '小高知宏', 'year': '2020', 'type': '技術書' },
    { 'id': 15, 'title': '「P≠NP」問題', 'author': '野崎昭弘', 'year': '2015', 'type': '数学書' },
    { 'id': 16, 'title': 'S BLUE', 'author': 'アンソロジー', 'year': '2010', 'type': 'ラノベ' },
    { 'id': 17, 'title': 'Schoof アルゴリズムによる超特異楕円曲線の自己準同型写像のトレース計算の高速化', 'author': '小峰和樹，片山瑛 and 安田雅哉', 'year': '2025', 'type': '論文' },
    { 'id': 18, 'title': 'Self-dual DeepBKZ for finding short lattice vectors', 'author': '安田雅哉', 'year': '2020', 'type': '論文' },
    { 'id': 19, 'title': 'Summer Vacation', 'author': 'いざね', 'year': '2024', 'type': '同人画集' },
    { 'id': 20, 'title': 'Speaking of Speech New Edition', 'author': 'David Harrington and Charles Le Beau', 'year': '2008', 'type': 'テキスト' },
    { 'id': 21, 'title': 'The Grimoir of Marisa', 'author': 'ZUN', 'year': '2009', 'type': '弾幕解説書' },
    { 'id': 22, 'title': 'Towards a Modern LLL Implementation', 'author': 'Léo Ducas，Ludo N. Pulles and Marc Stevens', 'year': '2025', 'type': '論文' },
    { 'id': 23, 'title': 'Unityの教科書', 'author': '北村愛美', 'year': '2019', 'type': '技術書' },
    { 'id': 24, 'title': 'Web学習アプリ対応\u3000C言語入門', 'author': '板谷雄二', 'year': '2019', 'type': '技術書' },
    { 'id': 25, 'title': 'What Do You Think?', 'author': '立教大学英語ディスカッション教育センター', 'year': '2010', 'type': 'テキスト' },
    { 'id': 26, 'title': '昭島市史', 'author': '昭島市史編さん委員会', 'year': '1978', 'type': '郷土史' },
    { 'id': 27, 'title': 'あなたと読む恋の歌百首', 'author': '俵万智', 'year': '2005', 'type': '歌集' },
    { 'id': 28, 'title': '入間郡誌', 'author': '安部立郎', 'year': '1913', 'type': '郷土史' },
    { 'id': 29, 'title': 'いわゆる天使の文化祭', 'author': '似鳥鶏', 'year': '2011', 'type': '小説' },
    { 'id': 30, 'title': '美しすぎる「数」の世界', 'author': '清水健一', 'year': '2017', 'type': '数学書' },
    { 'id': 31, 'title': 'オイラー〈ゼータ関数論文集〉', 'author': '黒川信重，小山信也，馬場郁 and 高田加代子', 'year': '2018', 'type': '数学書' },
    { 'id': 32, 'title': '改訂逗子町誌', 'author': '改訂逗子町誌刊行会', 'year': '1974', 'type': '郷土史' },
    { 'id': 33, 'title': '鏡音と双対空間', 'author': 'sekryy', 'year': '2024', 'type': '同人数学書' },
    { 'id': 34, 'title': '神楽歌\u3000催馬楽\u3000梁塵秘抄\u3000閑吟集', 'author': '臼田甚五郎 and 新間進一', 'year': '1976', 'type': '古典' },
    { 'id': 35, 'title': '学校を出よう！（１）', 'author': '谷川流', 'year': '2003', 'type': 'ラノベ' },
    { 'id': 36, 'title': '学校を出よう！（２）', 'author': '谷川流', 'year': '2003', 'type': 'ラノベ' },
    { 'id': 37, 'title': 'かなまいのイラスト集２', 'author': '金澤まい', 'year': '2023', 'type': '同人画集' },
    { 'id': 38, 'title': '神様のお仕事（１）', 'author': '幹', 'year': '2013', 'type': 'ラノベ' },
    { 'id': 39, 'title': '川角古墳群測量調査報告書', 'author': '駒澤大学考古学研究室', 'year': '2022', 'type': '調査報告書' },
    { 'id': 40, 'title': 'カラー図解\u3000古生物たちのふしぎな世界', 'author': '土屋健', 'year': '2017', 'type': '理工書' },
    { 'id': 41, 'title': '艦娘桟橋', 'author': 'C2機関', 'year': '2024', 'type': '雑誌付録' },
    { 'id': 42, 'title': '簡約変数の導入による虚二次体における格子基底簡約', 'author': '有元康一', 'year': '2019', 'type': '論文' },
    { 'id': 43, 'title': '北足立郡誌', 'author': '北足立郡役所', 'year': '1972', 'type': '郷土史' },
    { 'id': 44, 'title': 'きまぐれロボット', 'author': '星新一', 'year': '2014', 'type': '小説' },
    { 'id': 45, 'title': 'クジラと海とぼく', 'author': '水口博也', 'year': '2010', 'type': '小説' },
    { 'id': 46, 'title': 'クビキリサイクル', 'author': '西尾維新', 'year': '2008', 'type': '小説' },
    { 'id': 47, 'title': 'クビツリハイスクール', 'author': '西尾維新', 'year': '2008', 'type': '小説' },
    { 'id': 48, 'title': '群・環・体入門', 'author': '新妻弘 and 木村哲三', 'year': '1999', 'type': '数学書' },
    { 'id': 49, 'title': '群論入門', 'author': '芳沢光雄', 'year': '2015', 'type': '数学書' },
    { 'id': 50, 'title': '幻想地学博物誌', 'author': 'でんすけ', 'year': '2025', 'type': '同人誌' },
    { 'id': 51, 'title': '検地帳', 'author': '瑞穂町教育委員会', 'year': '1988', 'type': '郷土史' },
    { 'id': 52, 'title': '格子暗号解読のための数学的基礎', 'author': '青野良範 and 安田雅哉', 'year': '2019', 'type': '数学書' },
    { 'id': 53, 'title': '高次元空間を見る方法', 'author': '小笠英志', 'year': '2019', 'type': '数学書' },
    { 'id': 54, 'title': '格子と最適化手法を用いた素因数分解法の実験報告', 'author': '山口純平，伊豆哲也 and 國廣昇', 'year': '2023', 'type': '論文' },
    { 'id': 55, 'title': '古寺巡礼辞典', 'author': '中尾堯', 'year': '1973', 'type': 'じてん' },
    { 'id': 56, 'title': '国語辞典の名語釈', 'author': '武藤康史', 'year': '2008', 'type': '読み物' },
    { 'id': 57, 'title': '国分寺市史料集（Ⅱ）\u3000武蔵野新田開発関係文書\u3000川崎平右衛門関係文書', 'author': '国分寺市史編さん委員会', 'year': '1982', 'type': '郷土史' },
    { 'id': 58, 'title': '「国民抗戦必携」「国民築城必携」「国土決戦教令」', 'author': '藤田昌雄 and 佐山二郎', 'year': '2024', 'type': '古典' },
    { 'id': 59, 'title': '古代みちのく１０１の謎', 'author': '鈴木旭', 'year': '1995', 'type': '郷土史' },
    { 'id': 60, 'title': '児玉町史史料調査報告 第6集', 'author': '根岸篤太郎', 'year': '1980', 'type': '郷土史' },
    { 'id': 61, 'title': 'こちら、終末停滞委員会。（１）', 'author': '逢縁奇演', 'year': '2024', 'type': 'ラノベ' },
    { 'id': 62, 'title': 'こっきのえほん', 'author': '戸田やすし', 'year': '1987', 'type': '絵本' },
    { 'id': 63, 'title': 'コミュ障探偵の地味すぎる事件簿', 'author': '似鳥鶏', 'year': '2021', 'type': '小説' },
    { 'id': 64, 'title': '埼玉県広域道路地図', 'author': '東京人文社', 'year': '1992', 'type': '地図' },
    { 'id': 65, 'title': '埼玉\u3000地名の由来を歩く', 'author': '谷川彰英', 'year': '2017', 'type': '郷土史' },
    { 'id': 66, 'title': '埼玉の戦争遺跡', 'author': '関口和也', 'year': '2023郷土史', 'type': '郷土史' },
    { 'id': 67, 'title': 'サイバー攻撃', 'author': '中島明日香', 'year': '2018', 'type': '技術書' },
    { 'id': 68, 'title': '雑音まみれの哀悼歌', 'author': 'SAIFISU', 'year': '2025', 'type': 'ラノベ' },
    { 'id': 69, 'title': '狭山之栞', 'author': '杉本林志', 'year': '1939', 'type': '郷土史' },
    { 'id': 70, 'title': '字典かな', 'author': '笠間影印叢刊刊行会', 'year': '1972', 'type': 'じてん' },
    { 'id': 71, 'title': '春期限定いちごタルト事件', 'author': '米澤穂信', 'year': '2004', 'type': '小説' },
    { 'id': 72, 'title': '少女は書架の海で眠る', 'author': '支倉凍砂', 'year': '2015', 'type': 'ラノベ' },
    { 'id': 73, 'title': '小説 葬送のフリーレン: ~前奏~', 'author': '八目迷 and 山田鐘人', 'year': '2024', 'type': 'ラノベ' },
    { 'id': 74, 'title': '小説の小説', 'author': '似鳥鶏', 'year': '2022', 'type': '小説' },
    { 'id': 75, 'title': '新版\u3000基本統計学', 'author': '岡本雅典', 'year': '2012', 'type': '数学書' },
    { 'id': 76, 'title': '人類は衰退しました（１）', 'author': '田中ロミオ', 'year': '2007', 'type': 'ラノベ' },
    { 'id': 77, 'title': '人類は衰退しました（２）', 'author': '田中ロミオ', 'year': '2007', 'type': 'ラノベ' },
    { 'id': 78, 'title': '数学オリンピックチャンピオンの美しい解き方', 'author': 'Terence Tao and 寺嶋英志', 'year': '2010', 'type': '数学書' },
    { 'id': 79, 'title': '圖學概論', 'author': '須藤利一', 'year': '1961', 'type': '数学書' },
    { 'id': 80, 'title': '涼宮ハルヒの憂鬱', 'author': '谷川流', 'year': '2003', 'type': 'ラノベ' },
    { 'id': 81, 'title': '涼宮ハルヒの溜息', 'author': '谷川流', 'year': '2003', 'type': 'ラノベ' },
    { 'id': 82, 'title': '涼宮ハルヒの退屈', 'author': '谷川流', 'year': '2004', 'type': 'ラノベ' },
    { 'id': 83, 'title': '涼宮ハルヒの消失', 'author': '谷川流', 'year': '2004', 'type': 'ラノベ' },
    { 'id': 84, 'title': '涼宮ハルヒの暴走', 'author': '谷川流', 'year': '2004', 'type': 'ラノベ' },
    { 'id': 85, 'title': '涼宮ハルヒの動揺', 'author': '谷川流', 'year': '2005', 'type': 'ラノベ' },
    { 'id': 86, 'title': '涼宮ハルヒの陰謀', 'author': '谷川流', 'year': '2005', 'type': 'ラノベ' },
    { 'id': 87, 'title': '涼宮ハルヒの憤慨', 'author': '谷川流', 'year': '2006', 'type': 'ラノベ' },
    { 'id': 88, 'title': '涼宮ハルヒの分裂', 'author': '谷川流', 'year': '2007', 'type': 'ラノベ' },
    { 'id': 89, 'title': '涼宮ハルヒの驚愕（前）', 'author': '谷川流', 'year': '2011', 'type': 'ラノベ' },
    { 'id': 90, 'title': '涼宮ハルヒの驚愕（後）', 'author': '谷川流', 'year': '2011', 'type': 'ラノベ' },
    { 'id': 91, 'title': '涼宮ハルヒの直観', 'author': '谷川流', 'year': '2020', 'type': 'ラノベ' },
    { 'id': 92, 'title': '涼宮ハルヒの劇場', 'author': '谷川流', 'year': '2024', 'type': 'ラノベ' },
    { 'id': 93, 'title': '涼宮ハルヒの観測', 'author': 'スニーカー文庫編集部', 'year': '2011', 'type': 'ファンブック' },
    { 'id': 94, 'title': 'せいすうたん', 'author': '小林堂蟲 and 関真一朗', 'year': '2023', 'type': '数学書' },
    { 'id': 95, 'title': '整数と平面格子の数学', 'author': '桑田孝泰 and 前原濶', 'year': '2015', 'type': '数学書' },
    { 'id': 96, 'title': '戦国の比企\u3000境目の城', 'author': '埼玉県立嵐山史跡の博物館', 'year': '2020', 'type': '郷土史' },
    { 'id': 97, 'title': '双対格子への格子簡約適用によるENUMの計算量削減についての考察', 'author': '岸本共生，川添充 and 吉冨賢太郎', 'year': '2025', 'type': '論文' },
    { 'id': 98, 'title': '葬送のフリーレン\u3000画集\u3000vol.1', 'author': '山田鐘人 and アベツカサ', 'year': '2023', 'type': '画集' },
    { 'id': 99, 'title': '双対版DeepBKZ基底簡約の開発とLWEチャレンジ解読への適用', 'author': '安田雅哉，山口純平，大岡美智子 and 中邑聡史', 'year': '2018論文', 'type': '論文' },
    { 'id': 100, 'title': '代数曲線入門', 'author': '宮西正宜 and 増田佳代', 'year': '2016', 'type': '数学書' },
    { 'id': 101, 'title': '竹取物語（全）', 'author': '角川書店', 'year': '2001', 'type': '古典' },
    { 'id': 102, 'title': '秩父山間の歴史民俗', 'author': '飯塚好', 'year': '2018', 'type': '郷土史' },
    { 'id': 103, 'title': '秩父順拝記', 'author': '竹内立義', 'year': '1823', 'type': '日記' },
    { 'id': 104, 'title': '秩父日記', 'author': '渡辺渉園', 'year': '1853', 'type': '日記' },
    { 'id': 105, 'title': '地名アイヌ語小辞典', 'author': '知里真志保', 'year': '1956', 'type': 'じてん' },
    { 'id': 106, 'title': '中世史ハンドブック', 'author': '永原慶二 et al.', 'year': '1973', 'type': '古典' },
    { 'id': 107, 'title': '超動く家にて', 'author': '宮内悠介', 'year': '2021', 'type': '小説' },
    { 'id': 108, 'title': '超越数とはなにか', 'author': '西岡久美子', 'year': '2015', 'type': '数学書' },
    { 'id': 109, 'title': '「超」入門\u3000微分積分', 'author': '神永正博', 'year': '2012', 'type': '数学書' },
    { 'id': 110, 'title': '直観でわかるシュレーディンガー方程式', 'author': '岸野正剛', 'year': '2012', 'type': '理工書' },
    { 'id': 111, 'title': '鶴ケ島町史 近世資料編 1', 'author': '鶴ケ島町 (埼玉県)', 'year': '1982', 'type': '郷土史' },
    { 'id': 112, 'title': '東京府市区町村便覧', 'author': '東京地方改良協会', 'year': '1939', 'type': '地方自治' },
    { 'id': 113, 'title': '東方外来韋編', 'author': 'アスキー・メディアワークス', 'year': '2024', 'type': 'ムック本' },
    { 'id': 114, 'title': '東方求聞口授', 'author': 'ZUN', 'year': '2012', 'type': '設定資料集' },
    { 'id': 115, 'title': '東方求聞史紀', 'author': 'ZUN', 'year': '2007', 'type': '設定資料集' },
    { 'id': 116, 'title': '東方幻存神籤', 'author': 'ZUN', 'year': '2025', 'type': '設定資料集' },
    { 'id': 117, 'title': '東方文果真報', 'author': 'ZUN', 'year': '2017', 'type': '設定資料集' },
    { 'id': 118, 'title': '東方文花帖', 'author': 'ZUN', 'year': '2005', 'type': '設定資料集' },
    { 'id': 119, 'title': '毒物ずかん', 'author': 'くられ and 姫川たけお', 'year': '2018', 'type': '理工書' },
    { 'id': 120, 'title': '所沢町郷土史', 'author': '所沢市史編さん室', 'year': '1981', 'type': '郷土史' },
    { 'id': 121, 'title': 'ところざわ歴史物語\u3000増補改訂版', 'author': '所沢市教育委員会', 'year': '2020', 'type': '郷土史' },
    { 'id': 122, 'title': '長門有希ちゃんの消失\u3000とある一日', 'author': '新木伸，ぷよ and 谷川流', 'year': '2015', 'type': 'ラノベ' },
    { 'id': 123, 'title': 'なもり画集\u3000ゆるなもり', 'author': 'なもり', 'year': '2013', 'type': '画集' },
    { 'id': 124, 'title': 'ニコニコ動画における映像要約とサビ検出の試み', 'author': '青木秀憲 and 宮下芳明', 'year': '2008', 'type': '論文' },
    { 'id': 125, 'title': '日常の夏休み', 'author': '伊豆平成 and あらゐけいいち', 'year': '2014', 'type': '小説' },
    { 'id': 126, 'title': '日本妖怪異聞録', 'author': '小松和彦', 'year': '2007', 'type': '古典' },
    { 'id': 127, 'title': '日本列島の下では何が起きているのか', 'author': '中島淳一', 'year': '2018', 'type': '理工書' },
    { 'id': 128, 'title': '日本名所大地図', 'author': '株式会社平凡社', 'year': '2024', 'type': '地図' },
    { 'id': 129, 'title': '入門解剖図譜', 'author': '三井但夫', 'year': '1974', 'type': '医学書' },
    { 'id': 130, 'title': '博麗神社例大祭\u3000２０回記念誌', 'author': '博麗神社社務所', 'year': '2023', 'type': '同人画集' },
    { 'id': 131, 'title': '東久留米市文化財資料集（９）', 'author': '東久留米市教育委員会文化財課', 'year': '1983', 'type': '郷土史' },
    { 'id': 132, 'title': '東村山市農産物直売所めぐりマップ', 'author': '東村山市\u3000地域創生部\u3000産業振興課', 'year': '2021', 'type': '地図' },
    { 'id': 133, 'title': '東大和市史資料編 ９', 'author': '東大和市史編さん委員会', 'year': '1999', 'type': '郷土史' },
    { 'id': 134, 'title': 'ひだまりスケッチノベル\u3000ようこそひだまり荘へ', 'author': '日暮茶坊，蒼樹うめ', 'year': '2007', 'type': 'ラノベ' },
    { 'id': 135, 'title': 'ひだまりスケッチ\u3000ひだまりSchool Life', 'author': '日暮茶坊，蒼樹うめ', 'year': '2007', 'type': 'ラノベ' },
    { 'id': 136, 'title': '日野市史\u3000民俗編', 'author': '日野市史編さん委員会', 'year': '1983', 'type': '郷土史' },
    { 'id': 137, 'title': '檜原村紀聞', 'author': '瓜生卓造', 'year': '1996', 'type': '郷土史' },
    { 'id': 138, 'title': '秘々封々:Strawberry', 'author': '東風谷アオイ', 'year': '2023', 'type': '同人小説' },
    { 'id': 139, 'title': '微分方程式\u3000増補版', 'author': '原岡喜重', 'year': '2016', 'type': '数学書' },
    { 'id': 140, 'title': '氷菓', 'author': '米澤穂信', 'year': '2001', 'type': '小説' },
    { 'id': 141, 'title': '複素関数入門', 'author': '神保道夫', 'year': '2003', 'type': '数学書' },
    { 'id': 142, 'title': '複素関数論', 'author': '辻良平，柳原二郎，西尾和弘，佐藤シヅ子 and 吉田克明', 'year': '2011', 'type': '数学書' },
    { 'id': 143, 'title': '不自然な宇宙\u3000宇宙はひとつだけなのか？', 'author': '須藤靖', 'year': '2019', 'type': '理工書' },
    { 'id': 144, 'title': '富士見市石造文家財目録\u3000三\u3000富士見の馬頭観世音', 'author': '富士見市教育委員会', 'year': '2000', 'type': '郷土史' },
    { 'id': 145, 'title': '富士見のあゆみ', 'author': '富士見市立資料館', 'year': '2023', 'type': '郷土史' },
    { 'id': 146, 'title': '富士見の村絵図', 'author': '富士見市立難波田城資料館', 'year': '2004', 'type': '郷土史' },
    { 'id': 147, 'title': '物理数学の直観的方法\u3000〈普及版〉', 'author': '長沼伸一郎', 'year': '2011', 'type': '理工書' },
    { 'id': 148, 'title': 'プログラミングC#', 'author': 'Ian Griffiths，木下哲也 and 鈴木幸敏', 'year': '2021', 'type': '技術書' },
    { 'id': 149, 'title': 'ブロックチェーン', 'author': '岡崎裕史', 'year': '2019', 'type': '技術書' },
    { 'id': 150, 'title': '補習授業部と学ぶ数学\u3000場合の数・確率・統計', 'author': 'Azel', 'year': '2024', 'type': '同人数学書' },
    { 'id': 151, 'title': '宮河家の空腹', 'author': '待田堂子 and 美水かがみ', 'year': '2014', 'type': 'ラノベ' },
    { 'id': 152, 'title': '町田の地名のいわれ', 'author': '町田市立図書館', 'year': '1993', 'type': '郷土誌' },
    { 'id': 153, 'title': '未来いそっぷ', 'author': '星新一', 'year': '1982', 'type': '小説' },
    { 'id': 154, 'title': '無限の果てに何があるか', 'author': '足立恒雄', 'year': '2017', 'type': '理工書' },
    { 'id': 155, 'title': '武蔵野話', 'author': '齋藤鶴磯', 'year': '1970', 'type': '郷土史' },
    { 'id': 156, 'title': '村瀬のゼロからわかる地理B\u3000地誌編', 'author': '村瀬哲史', 'year': '2018', 'type': '参考書' },
    { 'id': 157, 'title': 'メールセキュリティ入門（１）', 'author': '山草', 'year': '2023', 'type': '同人技術書' },
    { 'id': 158, 'title': '化物語（上）', 'author': '西尾維新', 'year': '2006', 'type': '小説' },
    { 'id': 159, 'title': '化物語（下）', 'author': '西尾維新', 'year': '2006', 'type': '小説' },
    { 'id': 160, 'title': '傷物語', 'author': '西尾維新', 'year': '2008', 'type': '小説' },
    { 'id': 161, 'title': '愚物語', 'author': '西尾維新', 'year': '2015', 'type': '小説' },
    { 'id': 162, 'title': '短物語', 'author': '西尾維新', 'year': '2024', 'type': '小説' },
    { 'id': 163, 'title': 'もめんたりー・リリィ（１）', 'author': '八薙玉造 and GoHands×松竹', 'year': '2025', 'type': 'ラノベ' },
    { 'id': 164, 'title': '大和町史研究\u3000第8号', 'author': '大和町教育委員会', 'year': '1963', 'type': '郷土史' },
    { 'id': 165, 'title': 'ヤマノススメ\u3000アニメガイド\u3000おもいでビヨリ', 'author': 'KADOKAWA', 'year': '2023', 'type': 'アニメガイド' },
    { 'id': 166, 'title': '有限群の一様分解にまつわる諸問題', 'author': '品川和雅，金井和貴，宮本賢伍 and 縫田光司', 'year': '2025', 'type': '論文' },
    { 'id': 167, 'title': '妖精使いになる方法', 'author': 'アンソロジー', 'year': '2004', 'type': 'ラノベ' },
    { 'id': 168, 'title': '妖精配給会社', 'author': '星新一', 'year': '1976', 'type': '小説' },
    { 'id': 169, 'title': '読み書きで楽しく学ぶくずし字入門', 'author': '小林正博', 'year': '2019', 'type': 'テキスト' },
    { 'id': 170, 'title': 'らき☆すた\u300020th Anniversary\u3000イラストぶっく', 'author': '美水かがみ', 'year': '2023', 'type': '雑誌付録' },
    { 'id': 171, 'title': 'らき☆すた\u3000らき☆すたオンライン', 'author': '竹井10日 and 美水かがみ', 'year': '2008', 'type': 'ラノベ' },
    { 'id': 172, 'title': 'らき☆すた\u3000こなたの方程式', 'author': 'コンプティーク', 'year': '2007', 'type': 'ファンブック' },
    { 'id': 173, 'title': 'らき☆すた\u3000さいたま展\u3000完全ガイド', 'author': 'KADOKAWA', 'year': '2023', 'type': 'ムック本' },
    { 'id': 174, 'title': 'らき☆すた殺人事件', 'author': '竹井10日 and 美水かがみ', 'year': '2007', 'type': 'ラノベ' },
    { 'id': 175, 'title': 'らき☆すた\u3000スーパー童話大戦', 'author': '竹井10日 and 美水かがみ', 'year': '2008', 'type': 'ラノベ' },
    { 'id': 176, 'title': 'リーマン予想とはなにか', 'author': '中村亨', 'year': '2015', 'type': '数学書' },
    { 'id': 177, 'title': '量子計算を用いた素因数分解について', 'author': '伊豆哲也，山口純平 and 國廣昇', 'year': '2025', 'type': '論文' },
    { 'id': 178, 'title': '輪廻する宇宙\u3000ダークエネルギーに満ちた宇宙の将来', 'author': '横山順一', 'year': '2015', 'type': '理工書' },
    { 'id': 179, 'title': '歴史比較言語学入門', 'author': '下宮忠雄', 'year': '1999', 'type': '言語学書' },
    { 'id': 180, 'title': '論理と集合から始める数学の基礎', 'author': '嘉田勝', 'year': '2008', 'type': '数学書' }
];

</script>

<template>
    <Header />
    <p>
        ここでは，私の読んだ本について書いていきます．
        <br>取り敢えず一覧表みたいなものを作りたいですが，そのうち簡単な感想も載せるかも
        <br>※特に数学書や理工書，技術書などの中には読了していない本が多くあります．
    </p>
    <div>
        <VueGoodTable :columns="columns" :rows="rows" />
    </div>
    <Footer />
</template>